### ISSUE TITLE
Run error after clean installation.

### ISSUE THREAD

**Issue by Aske-Rosted** [icecube/graphnet#260]
The output below is an attempt at running the example train file after a fresh installation using the stand-alone installation guide for torch with GPU-support. 

```
(graphnet) [aske@hep04 graphnet]$ python examples/train_model.py
graphnet: INFO     2022-08-22 10:57:06 - get_logger - Writing log to logs/graphnet_20220822-105706.log
graphnet: WARNING  2022-08-22 10:57:06 - <module> - icecube package not available.
graphnet: WARNING  2022-08-22 10:57:06 - <module> - icecube package not available.
graphnet: WARNING  2022-08-22 10:57:07 - <module> - icecube package not available.
graphnet: WARNING  2022-08-22 10:57:07 - <module> - icecube package not available.
Traceback (most recent call last):
  File "examples/train_model.py", line 14, in <module>
    from graphnet.models import Model
  File "/lustre/hpc/hep/aske/IceCube/work/graphnet/src/graphnet/models/__init__.py", line 1, in <module>
    from .model import Model
  File "/lustre/hpc/hep/aske/IceCube/work/graphnet/src/graphnet/models/model.py", line 11, in <module>
    from graphnet.models.coarsening import Coarsening
  File "/lustre/hpc/hep/aske/IceCube/work/graphnet/src/graphnet/models/coarsening.py", line 12, in <module>
    from graphnet.components.pool import (
  File "/lustre/hpc/hep/aske/IceCube/work/graphnet/src/graphnet/components/pool.py", line 6, in <module>
    from torch_geometric.nn.pool.consecutive import consecutive_cluster
  File "/groups/hep/aske/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .sequential import Sequential
  File "/groups/hep/aske/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch_geometric/nn/sequential.py", line 9, in <module>
    from torch_geometric.nn.conv.utils.jit import class_from_module_repr
  File "/groups/hep/aske/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch_geometric/nn/conv/__init__.py", line 25, in <module>
    from .spline_conv import SplineConv
  File "/groups/hep/aske/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch_geometric/nn/conv/spline_conv.py", line 16, in <module>
    from torch_spline_conv import spline_basis, spline_weighting
  File "/groups/hep/aske/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch_spline_conv/__init__.py", line 15, in <module>
    torch.ops.load_library(spec.origin)
  File "/groups/hep/aske/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/groups/hep/aske/miniconda3/envs/graphnet/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /lustre/hpc/hep/aske/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch_spline_conv/_basis_cuda.so)
```

**Comment by asogaard** [comment]
Hi @Aske-Rosted,
Welcome! and thanks for this report. I have a PR-in-progress related to this, but I think the problem is the `torch-spline-conv` package, specifically, installing it from wheel on a system with too-old GLIBC (`$ ldd --version ldd` should be >= 2.27). The simplest solution should just be to `$ pip uninstall torch-spline-conv` (my PR will remove it from `setup.py` and the requirements files) — I don't think we're using it anywhere anyway, but perhaps @RasmusOrsoe can confirm.

**Comment by Aske-Rosted** [comment]
After a quick rerun i can confirm that the solution seemingly works.

**Comment by RasmusOrsoe** [comment]
`torch-spline-conv `is a support package that used to be required by `torch geometric`.  Today it's optional. I think we need to be very aware of what functionality in PyG we won't support if we remove this.

![billede](https://user-images.githubusercontent.com/48880272/185905187-456dc154-d1aa-4b7b-8c71-6a9fa0c96e5e.png)

**Comment by asogaard** [comment]
From what I can tell, we'll be losing support for a single convolutional operator (`SplineConv`, https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.SplineConv) by not installing this package by default. I think this is an acceptable trade-off for now, if the alternative is spending more time tinkering with the setup procedure. If we find a good way to more elegantly handle the setup, specifically on the ancient NBI HEP machines, I am totally in favour of including this package again.

**Comment by RasmusOrsoe** [comment]
@asogaard I agree. Thanks for checking up on that.
