### ISSUE TITLE
Problem running train_model after fresh install

### ISSUE THREAD

**Issue by Peterandresen12** [icecube/graphnet#267]
**Describe the bug**
I encountered the following issue when trying to run the train_model file in examples. I installed Graphnet using the standalone installation guide. I also added the `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/anaconda3/lib/` to my bashrc file.

The error message looks like this: 
```
(graphnet) [peter@hep04 examples]$ python train_model.py 
graphnet: INFO     2022-08-29 11:06:33 - get_logger - Writing log to logs/graphnet_20220829-110633.log
graphnet: WARNING  2022-08-29 11:06:33 - <module> - icecube package not available.
graphnet: WARNING  2022-08-29 11:06:33 - <module> - icecube package not available.
graphnet: WARNING  2022-08-29 11:06:33 - <module> - icecube package not available.
graphnet: WARNING  2022-08-29 11:06:33 - <module> - icecube package not available.
Traceback (most recent call last):
  File "train_model.py", line 11, in <module>
    from graphnet.data.sqlite.sqlite_selection import (
  File "/lustre/hpc/icecube/peter/workspace/graphnetgit/graphnet/src/graphnet/data/sqlite/__init__.py", line 2, in <module>
    from .sqlite_dataset import SQLiteDataset
  File "/lustre/hpc/icecube/peter/workspace/graphnetgit/graphnet/src/graphnet/data/sqlite/sqlite_dataset.py", line 5, in <module>
    from graphnet.data.dataset import Dataset, ColumnMissingException
  File "/lustre/hpc/icecube/peter/workspace/graphnetgit/graphnet/src/graphnet/data/dataset.py", line 7, in <module>
    from torch_geometric.data import Data
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch_geometric/data/data.py", line 9, in <module>
    from torch_sparse import SparseTensor
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory
```

**Comment by asogaard** [comment]
Hi @Peterandresen12,

Thanks for raising this issue! Could you try to run
```bash
$ conda install cudatoolkit=11.5 -c conda-forge
```
in your activated `graphnet` conda environment?

**Comment by Peterandresen12** [comment]
Hi @asogaard,

I tried running your suggestion, but it did not solve the issue. 

This is what the installation looked like: 

```
(graphnet) [peter@hep04 examples]$ conda install cudatoolkit=11.5 -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /groups/icecube/peter/anaconda3/envs/graphnet

  added / updated specs:
    - cudatoolkit=11.5


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.6.15  |       ha878542_0         149 KB  conda-forge
    certifi-2022.6.15          |     pyhd8ed1ab_1         154 KB  conda-forge
    cudatoolkit-11.5.1         |      h59c8dcf_10       798.9 MB  conda-forge
    openssl-1.1.1o             |       h166bdaf_0         2.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       801.4 MB

The following NEW packages will be INSTALLED:

  cudatoolkit        conda-forge/linux-64::cudatoolkit-11.5.1-h59c8dcf_10

The following packages will be UPDATED:

  certifi            pkgs/main/linux-64::certifi-2022.6.15~ --> conda-forge/noarch::certifi-2022.6.15-pyhd8ed1ab_1

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2022.07.19~ --> conda-forge::ca-certificates-2022.6.15-ha878542_0
  openssl              pkgs/main::openssl-1.1.1q-h7f8727e_0 --> conda-forge::openssl-1.1.1o-h166bdaf_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
ca-certificates-2022 | 149 KB    | ##################################################################### | 100% 
openssl-1.1.1o       | 2.1 MB    | ##################################################################### | 100% 
cudatoolkit-11.5.1   | 798.9 MB  | ##################################################################### | 100% 
certifi-2022.6.15    | 154 KB    | ##################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: / By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
```

I then receive the same error message as above, when trying to execute train_model in examples.

**Comment by Peterandresen12** [comment]
Hi again @asogaard.
I got it to work by running your suggestion: 
```
conda install cudatoolkit=11.5 -c conda-forge
```

And by updating the line that is added to the .bashrc during standalone installation from: 
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/anaconda3/lib/` to either 

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/anaconda3/envs/graphnet/lib/` 
or 
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/miniconda3/envs/graphnet/lib/`  
depending on whether you use anaconda or miniconda.

**Comment by asogaard** [comment]
Thanks for the debugging, @Peterandresen12. I have updated the README accordingly.
