### ISSUE TITLE
Trouple running with accelerators on training sample

### ISSUE THREAD

**Issue by Peterandresen12** [icecube/graphnet#274]
I have issues running train_model from examples on a CPU and GPU number 1. 

I have tried to run on Hep02 using a CPU, in the following ways.

1) `"accelerator": "cpu",
        "devices": [],`
2) `"accelerator": "cpu",
        "devices": [0],`
3) `"accelerator": "cpu",
        "devices": [1],`
4) `"accelerator": "gpu",
        "devices": [],`
5) `"accelerator": "gpu",
        "devices": [0],`

And i get the following errors:
1) 
```
/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py:22: LightningDeprecationWarning: pytorch_lightning.core.lightning.LightningModule has been deprecated in v1.7 and will be removed in v1.9. Use the equivalent class from the pytorch_lightning.core.module.LightningModule class instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "train_model.py", line 157, in <module>
    main()
  File "train_model.py", line 128, in main
    trainer = Trainer(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
    return fn(self, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 433, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 201, in __init__
    self._check_device_config_and_set_final_flags(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 414, in _check_device_config_and_set_final_flags
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: `Trainer(devices=[])` value is not a valid input using cpu accelerator.
```
2)
```
/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py:22: LightningDeprecationWarning: pytorch_lightning.core.lightning.LightningModule has been deprecated in v1.7 and will be removed in v1.9. Use the equivalent class from the pytorch_lightning.core.module.LightningModule class instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "train_model.py", line 157, in <module>
    main()
  File "train_model.py", line 128, in main
    trainer = Trainer(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
    return fn(self, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 433, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 213, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 544, in _set_parallel_devices_and_init_accelerator
    self._devices_flag = self.accelerator.parse_devices(self._devices_flag)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu.py", line 45, in parse_devices
    devices = device_parser.parse_cpu_cores(devices)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 173, in parse_cpu_cores
    raise MisconfigurationException("`devices` selected with `CPUAccelerator` should be an int > 0.")
pytorch_lightning.utilities.exceptions.MisconfigurationException: `devices` selected with `CPUAccelerator` should be an int > 0.
```

3)
```
/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py:22: LightningDeprecationWarning: pytorch_lightning.core.lightning.LightningModule has been deprecated in v1.7 and will be removed in v1.9. Use the equivalent class from the pytorch_lightning.core.module.LightningModule class instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "train_model.py", line 157, in <module>
    main()
  File "train_model.py", line 128, in main
    trainer = Trainer(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
    return fn(self, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 433, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 213, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 544, in _set_parallel_devices_and_init_accelerator
    self._devices_flag = self.accelerator.parse_devices(self._devices_flag)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu.py", line 45, in parse_devices
    devices = device_parser.parse_cpu_cores(devices)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", line 173, in parse_cpu_cores
    raise MisconfigurationException("`devices` selected with `CPUAccelerator` should be an int > 0.")
pytorch_lightning.utilities.exceptions.MisconfigurationException: `devices` selected with `CPUAccelerator` should be an int > 0.
```

4)
```
/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py:22: LightningDeprecationWarning: pytorch_lightning.core.lightning.LightningModule has been deprecated in v1.7 and will be removed in v1.9. Use the equivalent class from the pytorch_lightning.core.module.LightningModule class instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "train_model.py", line 157, in <module>
    main()
  File "train_model.py", line 128, in main
    trainer = Trainer(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
    return fn(self, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 433, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 201, in __init__
    self._check_device_config_and_set_final_flags(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 414, in _check_device_config_and_set_final_flags
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: `Trainer(devices=[])` value is not a valid input using gpu accelerator.
```

5)
```
/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py:22: LightningDeprecationWarning: pytorch_lightning.core.lightning.LightningModule has been deprecated in v1.7 and will be removed in v1.9. Use the equivalent class from the pytorch_lightning.core.module.LightningModule class instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "train_model.py", line 157, in <module>
    main()
  File "train_model.py", line 128, in main
    trainer = Trainer(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
    return fn(self, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 433, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 211, in __init__
    self._accelerator_flag = self._choose_gpu_accelerator_backend()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 517, in _choose_gpu_accelerator_backend
    raise MisconfigurationException("No supported gpu backend found!")
pytorch_lightning.utilities.exceptions.MisconfigurationException: No supported gpu backend found!
```

I do not encounter issues when running on Hep04 GPU number 0, but when I try to run on GPU number 1, I get the following error message:

```
/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py:22: LightningDeprecationWarning: pytorch_lightning.core.lightning.LightningModule has been deprecated in v1.7 and will be removed in v1.9. Use the equivalent class from the pytorch_lightning.core.module.LightningModule class instead.
  rank_zero_deprecation(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "train_model.py", line 157, in <module>
    main()
  File "train_model.py", line 138, in main
    trainer.fit(model, training_dataloader, validation_dataloader)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1147, in _run
    self.strategy.setup(self)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/strategies/single_device.py", line 73, in setup
    self.model_to_device()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/strategies/single_device.py", line 70, in model_to_device
    self.model.to(self.root_device)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/core/mixins/device_dtype_mixin.py", line 113, in to
    return super().to(*args, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by asogaard** [comment]
Hi @Peterandresen12,

* Items 1 and 4 fail because an empty list (`[]`) is not a valid argument for `devices` in the pytorch-lightning `Trainer` class, see [here](https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#devices). It should be an integer (i.e., number of devices), a non-empty list of integers (i.e., specific devices by index), or `"auto"` (default, I believe).
* Items 4 and 5 fail, because there is no GPU on `hep02`.
* Items 2 and 3 fail, as the error message says, because `MisconfigurationException: 'devices' selected with 'CPUAccelerator' should be an int > 0.` but a list is provided. 

If you're running on a CPU-only machine, you should be able to say, e.g., `accelerator="cpu", devices=1`, or set both arguments to `"auto"`, or simply remove them from the constructor.

If you're running on a GPU machine, you should be able to say `accelerator="gpu", devices=[0]` or `[1]`, `1`, `2`, or `"auto"`. The fact that using `devices=[1]` fails on hep04 with error `CUDA error: out of memory` is either that someone else is using that GPU (run `$ nvidia-smi` in your terminal and check the utilisation of both GPUs before launching a run) or because it is stuck with stuff in memory from a previous, failed run. If the latter is the case, and the problem persists, we can have it reset by IT at UCPH.
