### ISSUE TITLE
Error when saving results in train_model.py

### ISSUE THREAD

**Issue by MoustHolmes** [icecube/graphnet#281]
**Describe the bug**
When I try to run train_model.py everything runs except the last line where we save the results using the function save_results.
If I out-comment the last line the whole script runs without problems.
the error seams to occurs when we use the pytorch function model.save() within the save_results function which won't pickle a "sqlite3.Connection" ?

**Traceback**
```
Traceback (most recent call last):
  File "train_model.py", line 155, in <module>
    main()
  File "train_model.py", line 150, in main
    save_results(config["db"], run_name, results, archive, model)
  File "/lustre/hpc/icecube/moust/work/graphnet/src/graphnet/models/training/utils.py", line 206, in save_results
    model.save(path + "/" + tag + "_model.pth")
  File "/lustre/hpc/icecube/moust/work/graphnet/src/graphnet/models/model.py", line 147, in save
    torch.save(self.cpu(), path, pickle_module=dill)
  File "/groups/icecube/moust/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/serialization.py", line 380, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/groups/icecube/moust/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/serialization.py", line 589, in _save
    pickler.dump(obj)
  File "/groups/icecube/moust/miniconda3/envs/graphnet/lib/python3.8/site-packages/dill/_dill.py", line 620, in dump
    StockPickler.dump(self, obj)
  File "/groups/icecube/moust/miniconda3/envs/graphnet/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
```

After this, there are like 50 lines of slight variations of the last line with this being the last line

```
TypeError: cannot pickle 'sqlite3.Connection' object
```

**Comment by MortenHolmRep** [comment]
I updated the framework to the recent iteration and get somewhat the same error as @MoustHolmes when running inference.
```
Traceback (most recent call last):
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/lustre/hpc/icecube/qgf305/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/lustre/hpc/icecube/qgf305/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/lustre/hpc/icecube/qgf305/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/groups/icecube/qgf305/work/graphnet/studies/Moon_Pointing_Analysis/deployment/run_inference_on_sqlite.py", line 146, in <module>
    main(input_db, output_folder, model_path)
  File "/groups/icecube/qgf305/work/graphnet/studies/Moon_Pointing_Analysis/deployment/run_inference_on_sqlite.py", line 136, in main
    save_results(config["db"], run_name, results, archive, model)
  File "/lustre/hpc/icecube/qgf305/work/graphnet/src/graphnet/models/training/utils.py", line 215, in save_results
    model.save(path + "/" + tag + "_model.pth")
  File "/lustre/hpc/icecube/qgf305/work/graphnet/src/graphnet/models/model.py", line 147, in save
    torch.save(self.cpu(), path, pickle_module=dill)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch/serialization.py", line 380, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch/serialization.py", line 589, in _save
    pickler.dump(obj)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/site-packages/dill/_dill.py", line 620, in dump
    StockPickler.dump(self, obj)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/site-packages/dill/_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/site-packages/dill/_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/site-packages/dill/_dill.py", line 1724, in save_weakproxy
    pickler.save_reduce(_create_weakproxy, (refobj, callable), obj=obj)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 692, in save_reduce
    save(args)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 886, in save_tuple
    save(element)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/site-packages/dill/_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/site-packages/dill/_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/site-packages/dill/_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/site-packages/dill/_dill.py", line 1251, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/pickle.py", line 578, in save
    rv = reduce(self.proto)
  File "/groups/icecube/qgf305/anaconda3/envs/graphnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 556, in __getstate__
    raise NotImplementedError("{} cannot be pickled", self.__class__.__name__)
NotImplementedError: ('{} cannot be pickled', '_MultiProcessingDataLoaderIter')
```

**Comment by asogaard** [comment]
Hi @MoustHolmes and @MortenHolmRep,
What version of pytorch-lightning are you using? I have encountered this error before, and did a clumsy workaround, but I just checked out the `main` branch and updated pytorch-lightning to `1.7.7` and was able to run the `train_model.py` script without any issues.

**Comment by MoustHolmes** [comment]
I was using PyTorch-lightning 1.5.6 but updating to 1.7.7 still gives the same error

**Comment by asogaard** [comment]
Cheers! What about the other torch packages? Could you paste the outputs of running `$ pip list | grep torch` in your terminal in the environment in which you are running the example?

**Comment by MoustHolmes** [comment]
```
pytorch-lightning             1.7.7
torch                         1.11.0+cu115
torch-cluster                 1.6.0
torch-geometric               2.0.4
torch-scatter                 2.0.9
torch-sparse                  0.6.13
torchmetrics                  0.9.3 
```

**Comment by asogaard** [comment]
Cheers! Alright, could you then do me a favour by:

* Going to [your fork](https://github.com/MoustHolmes/graphnet) and click the "Sync fork" > "Update branch" right below the green "Code" button. This bring your `main` branch up to date with `graphnet-team/graphnet:main`.
* In your terminal, switching to the main branch if you're not already on it (`$ git checkout main`) and pull the sync'ed changes from the remote (i.e., from your fork on github.com; `$ git pull`).
* Then running the `train_model.py` script again.

The above steps are just to ensure that we are comparing apples to apples as I'll be trying to resolve this issue. :)
